# Generated by Django 4.2.4 on 2023-08-11 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Joints',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('joint', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('img_path', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('arabic_description', models.TextField()),
                ('swahili_description', models.TextField()),
                ('chinese_description', models.TextField()),
                ('img_path', models.CharField(max_length=200)),
                ('joint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rehabs.joints')),
            ],
        ),
    ]
