# Generated by Django 4.2.4 on 2023-08-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehabs', '0002_alter_contact_id_alter_joints_id_alter_people_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='linkedin',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
